/* 
 * Switch Database REST API
 *
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WhereItem
    /// </summary>
    [DataContract]
    public partial class WhereItem :  IEquatable<WhereItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WhereItem" /> class.
        /// </summary>
        /// <param name="Type">You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan.</param>
        /// <param name="Column">Column name.</param>
        /// <param name="Value">Column value.</param>
        public WhereItem(string Type = default(string), string Column = default(string), string Value = default(string))
        {
            this.Type = Type;
            this.Column = Column;
            this.Value = Value;
        }
        
        /// <summary>
        /// You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan
        /// </summary>
        /// <value>You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }
        /// <summary>
        /// Column name
        /// </summary>
        /// <value>Column name</value>
        [DataMember(Name="column", EmitDefaultValue=false)]
        public string Column { get; set; }
        /// <summary>
        /// Column value
        /// </summary>
        /// <value>Column value</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WhereItem {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Column: ").Append(Column).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as WhereItem);
        }

        /// <summary>
        /// Returns true if WhereItem instances are equal
        /// </summary>
        /// <param name="other">Instance of WhereItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WhereItem other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                ) && 
                (
                    this.Column == other.Column ||
                    this.Column != null &&
                    this.Column.Equals(other.Column)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                if (this.Column != null)
                    hash = hash * 59 + this.Column.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
