/* 
 * Switch Database REST API
 *
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BodyTests
    {
        // TODO uncomment below to declare an instance variable for Body
        //private Body instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body
            //instance = new Body();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body
        /// </summary>
        [Test]
        public void BodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body
            //Assert.IsInstanceOfType<Body> (instance, "variable 'instance' is a Body");
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Test]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'WhereType'
        /// </summary>
        [Test]
        public void WhereTypeTest()
        {
            // TODO unit test for the property 'WhereType'
        }
        /// <summary>
        /// Test the property 'Where'
        /// </summary>
        [Test]
        public void WhereTest()
        {
            // TODO unit test for the property 'Where'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
