/* 
 * Switch Database REST API
 *
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SetResponseTests
    {
        // TODO uncomment below to declare an instance variable for SetResponse
        //private SetResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetResponse
            //instance = new SetResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetResponse
        /// </summary>
        [Test]
        public void SetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SetResponse
            //Assert.IsInstanceOfType<SetResponse> (instance, "variable 'instance' is a SetResponse");
        }

        /// <summary>
        /// Test the property 'ResponseTime'
        /// </summary>
        [Test]
        public void ResponseTimeTest()
        {
            // TODO unit test for the property 'ResponseTime'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

    }

}
